# MySQL Role Handlers

---
- name: restart mysql
  systemd:
    name: mysql
    state: restarted
  become: true

- name: restart mariadb
  systemd:
    name: mariadb
    state: restarted
  become: true

- name: reload mysql
  systemd:
    name: mysql
    state: reloaded
  become: true
